[project]
name = "ai-workshop-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.4.3",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
]
